/* Generated by S-function Builder */
#ifndef _SFBUILDER_BUS_BUS_H_
#define _SFBUILDER_BUS_BUS_H_
/* Read only - STARTS */
#include "tmwtypes.h"




#ifndef _DEFINED_TYPEDEF_FOR_SFB_LIMITBUS_
#define _DEFINED_TYPEDEF_FOR_SFB_LIMITBUS_ 
typedef struct {
  int32_T upper_saturation_limit;
  int32_T lower_saturation_limit;
} SFB_LIMITBUS;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_SFB_SIGNALBUS_
#define _DEFINED_TYPEDEF_FOR_SFB_SIGNALBUS_ 
typedef struct {
  int32_T input;
} SFB_SIGNALBUS;
#endif


#ifndef _DEFINED_TYPEDEF_FOR_SFB_COUNTERBUS_
#define _DEFINED_TYPEDEF_FOR_SFB_COUNTERBUS_ 
typedef struct {
  SFB_SIGNALBUS inputsignal;
  SFB_LIMITBUS limits;
} SFB_COUNTERBUS;
#endif

/* Read only - ENDS */


#endif
